### ISSUE TITLE
gulp-image breaks things

### ISSUE THREAD

**Issue by rogerhutchings** [Granze/react-starterify#19]
Some of my coworkers were trying this out and came across a bug, so I thought I'd log it. On a fresh checkout, `gulp-image` throws an error: 

```
[BS] 2 files changed (main.css.map, main.css)
child_process.js:1136
  var err = this._handle.spawn(options);
                         ^
TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (child_process.js:1136:26)
    at exports.spawn (child_process.js:995:9)
    at exports.execFile (child_process.js:689:15)
    at /Volumes/Projects/react-starterify/node_modules/gulp-image/optimizer.js:241:7
    at /Volumes/Projects/react-starterify/node_modules/gulp-image/node_modules/async/lib/async.js:713:13
    at iterate (/Volumes/Projects/react-starterify/node_modules/gulp-image/node_modules/async/lib/async.js:262:13)
    at /Volumes/Projects/react-starterify/node_modules/gulp-image/node_modules/async/lib/async.js:274:29
    at /Volumes/Projects/react-starterify/node_modules/gulp-image/node_modules/async/lib/async.js:44:16
    at /Volumes/Projects/react-starterify/node_modules/gulp-image/node_modules/async/lib/async.js:718:17
```

**Comment by Granze** [comment]
Hi, I was already thinking to replace this plugin because it seems that is now flagged as deprecated.
I'll try to replace it this evening if I have some spare time.

Thanks for your feedback, I'll let you know ASAP.

**Comment by rogerhutchings** [comment]
No worries - I think they mentioned [sindresorhus/gulp-imagemin](https://github.com/sindresorhus/gulp-imagemin) working

**Comment by Granze** [comment]
I just moved to gulp-imagemin.

Check out the new release and let me know if it's works for you, thanks. :)

**Comment by rogerhutchings** [comment]
Seems legit - thanks!
