### ISSUE TITLE
Cannot find module core-js/shim

### ISSUE THREAD

**Issue by samueledirito** [Granze/react-starterify#20]
Sorry, but i'm not able to make it start.

This is the stacktrace when i start tests:

> react-starterify@2.0.0 test C:\Projects\react-test
> mocha --reporter nyan --compilers js:babel/register --recursive

module.js:338
    throw err;
          ^
Error: Cannot find module 'core-js/shim'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Projects\react-test\node_modules\babel-core\lib\polyfill.js:3:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Projects\react-test\node_modules\babel-core\lib\api\register\node-polyfill.js:8:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Projects\react-test\node_modules\babel-core\register.js:1:80)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Projects\react-test\node_modules\babel\register.js:1:80)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at C:\Projects\react-test\node_modules\mocha\bin\_mocha:296:3
    at Array.forEach (native)
    at Object.<anonymous> (C:\Projects\react-test\node_modules\mocha\bin\_mocha:290:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! react-starterify@2.0.0 test: `mocha --reporter nyan --compilers js:babel/register --recursive`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-starterify@2.0.0 test script 'mocha --reporter nyan --compilers js:babel/register --recursive'.
npm ERR! This is most likely a problem with the react-starterify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha --reporter nyan --compilers js:babel/register --recursive
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-starterify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projects\react-test\npm-debug.log

And this is the stacktrace when i run gulp watch:

C:\Projects\react-test>gulp watch
[17:45:01] Failed to load external module babel-core/register
[17:45:01] Failed to load external module babel/register
C:\Projects\react-test\gulpfile.babel.js:1
(function (exports, require, module, __filename, __dirname) { import gulp from
                                                              ^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (C:\Users\Samuele\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> (C:\Users\Samuele\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:192:16)
    at module.exports (C:\Users\Samuele\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\node_modules\flagged-respawn\index.js:17:3)

Can anyone help? Thank you veeeeeery much!

**Comment by Granze** [comment]
I just tried a clean install on Mac OSX and Linux and it works. Unfortunately I don't have the possibility to try it on a Windows machine. 
Anyway I'll try to look into this.
